packages:
  - "packages/*"
  - "tests/e2e"
  - "tests/e2e/react-app"
  - "tests/e2e/svelte-app"
  - "tests/e2e/lit-app"
  - "tests/e2e/vue-app"
  - "tests/e2e/angular-app"
  - "tests/e2e/solid-app"
  - "tests/e2e/preact-app"
  - "tests/e2e/ember-app"
  - "docs-web"
